service: olivia-challenge
provider:
  name: openwhisk
  runtime: java
package:
 artifact: target/olivia-challenge.jar
functions:
  bet:
    handler: target/olivia-challenge.jar:br.com.evandropires.oliviachallenge.function.BetFunction
    name: oliviachallenge/bet
plugins:
  - "serverless-openwhisk"