/*
 * This file is generated by jOOQ.
 */
package br.com.evandropires.oliviachallenge.jooq.tables.records;


import br.com.evandropires.oliviachallenge.jooq.tables.Bet;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BetRecord extends UpdatableRecordImpl<BetRecord> implements Record7<Integer, String, String, BigDecimal, BigDecimal, Timestamp, Boolean> {

    private static final long serialVersionUID = -526949134;

    /**
     * Setter for <code>public.bet.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.bet.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.bet.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.bet.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.bet.email</code>.
     */
    public void setEmail(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.bet.email</code>.
     */
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.bet.height</code>.
     */
    public void setHeight(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.bet.height</code>.
     */
    public BigDecimal getHeight() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>public.bet.weight</code>.
     */
    public void setWeight(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.bet.weight</code>.
     */
    public BigDecimal getWeight() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>public.bet.born</code>.
     */
    public void setBorn(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.bet.born</code>.
     */
    public Timestamp getBorn() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>public.bet.hairy</code>.
     */
    public void setHairy(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.bet.hairy</code>.
     */
    public Boolean getHairy() {
        return (Boolean) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, BigDecimal, BigDecimal, Timestamp, Boolean> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, BigDecimal, BigDecimal, Timestamp, Boolean> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Bet.BET.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Bet.BET.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Bet.BET.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field4() {
        return Bet.BET.HEIGHT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field5() {
        return Bet.BET.WEIGHT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return Bet.BET.BORN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field7() {
        return Bet.BET.HAIRY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component4() {
        return getHeight();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component5() {
        return getWeight();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getBorn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component7() {
        return getHairy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value4() {
        return getHeight();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value5() {
        return getWeight();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getBorn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value7() {
        return getHairy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BetRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BetRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BetRecord value3(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BetRecord value4(BigDecimal value) {
        setHeight(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BetRecord value5(BigDecimal value) {
        setWeight(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BetRecord value6(Timestamp value) {
        setBorn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BetRecord value7(Boolean value) {
        setHairy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BetRecord values(Integer value1, String value2, String value3, BigDecimal value4, BigDecimal value5, Timestamp value6, Boolean value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BetRecord
     */
    public BetRecord() {
        super(Bet.BET);
    }

    /**
     * Create a detached, initialised BetRecord
     */
    public BetRecord(Integer id, String name, String email, BigDecimal height, BigDecimal weight, Timestamp born, Boolean hairy) {
        super(Bet.BET);

        set(0, id);
        set(1, name);
        set(2, email);
        set(3, height);
        set(4, weight);
        set(5, born);
        set(6, hairy);
    }
}
