/*
 * This file is generated by jOOQ.
 */
package br.com.evandropires.oliviachallenge.jooq;


import br.com.evandropires.oliviachallenge.jooq.tables.Bet;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index BET_PKEY = Indexes0.BET_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index BET_PKEY = Internal.createIndex("bet_pkey", Bet.BET, new OrderField[] { Bet.BET.ID }, true);
    }
}
