/*
 * This file is generated by jOOQ.
 */
package br.com.evandropires.oliviachallenge.jooq;


import br.com.evandropires.oliviachallenge.jooq.tables.Bet;
import br.com.evandropires.oliviachallenge.jooq.tables.records.BetRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<BetRecord, Integer> IDENTITY_BET = Identities0.IDENTITY_BET;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<BetRecord> BET_PKEY = UniqueKeys0.BET_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<BetRecord, Integer> IDENTITY_BET = Internal.createIdentity(Bet.BET, Bet.BET.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<BetRecord> BET_PKEY = Internal.createUniqueKey(Bet.BET, "bet_pkey", Bet.BET.ID);
    }
}
