/*
 * This file is generated by jOOQ.
 */
package br.com.evandropires.oliviachallenge.jooq;


import br.com.evandropires.oliviachallenge.jooq.tables.Bet;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.bet</code>.
     */
    public static final Bet BET = br.com.evandropires.oliviachallenge.jooq.tables.Bet.BET;
}
